### ISSUE TITLE
asasas

### ISSUE THREAD

**Issue by dublinboy7** [najmlion/java#2]
public void stateChanged(ChangeEvent e) {
				int duration = Integer.parseInt(((SpinnerNumberModel)e.getSource()).getValue().toString());
				SimpleDateFormat formatTime = new SimpleDateFormat("kk:mm");
				String spinnerTime = formatTime.format(modelTime.getValue());
				Date d = new Date();
				try {
					d = formatTime.parse(spinnerTime);
				} catch (ParseException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				Calendar cal = Calendar.getInstance();
				cal.setTime(d);

**Comment by najmlion** [comment]
ok you do this

**Comment by dublinboy7** [comment]
Fuck Farrah

**Comment by najmlion** [comment]
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.*;

public class AddProductGUI extends JFrame {
	   private JLabel lblLogo, lblName, lblType, lblQuantity, lblCostPrice, lblSellingPrice;
	   private JTextField txtName, txtQuantity, txtCostPrice, txtSellingPrice;
	   private JComboBox<String> comboItemType; 
	   private JButton btnAdd, btnView;
	
	   
	   private JPanel pnlDisplay,pnlInput, pnlBtns;
	   private String[] itemType = { "Desktop", "Laptop", "Accessories" };
	   
	   private JMenu mMain;;
	   private JMenuItem miView, miExit;
       private JMenuBar bar;
       private ViewProductGUI child;
	   private ArrayList products;

	   public AddProductGUI() {
		   this.setDefaultCloseOperation(EXIT_ON_CLOSE);
		   createMenuGUI();
		   createGUI();
	   }
	   public void createMenuGUI()
	   {
		   
		 //create menu, items and menu bar
		   bar=new JMenuBar();
		   mMain=new JMenu("Menu");
		   miView=new JMenuItem("View");
		   miExit=new JMenuItem("Exit");
		   
		   mMain.add(miView);
		   mMain.add(miExit);
		   
		   bar.add(mMain);
		   setJMenuBar(bar);
	   }
	   
	   private void createGUI() {
		//create components and to containers
		   
		   pnlDisplay=new JPanel();
		   lblLogo=new JLabel(new ImageIcon("logo.jpg"));
		   pnlDisplay.add(lblLogo);
		   this.add(pnlDisplay, BorderLayout.NORTH);
		   
		 //array
		   products=new ArrayList<Product>();
		   
		   pnlInput=new JPanel(new GridLayout(5, 2));
		   lblName=new JLabel("Item Name: ");
		   lblType=new JLabel("Item Type: ");
		   lblQuantity=new JLabel("Item Quantity:");
		   lblCostPrice=new JLabel("Cost Price:");
		   lblSellingPrice = new JLabel("Selling Price: ");
		   
		   
		   txtName=new JTextField(10);
		   txtQuantity=new JTextField(10);
		   txtCostPrice=new JTextField(10);
		   txtSellingPrice=new JTextField(10);
		   comboItemType= new JComboBox<String>(itemType);
		   
		   
		   pnlInput.add(lblName);
		   pnlInput.add(txtName);
		   pnlInput.add(lblType);
		   pnlInput.add(comboItemType);
		   pnlInput.add(lblQuantity);
		   pnlInput.add(txtQuantity);
		   pnlInput.add(lblCostPrice);
		   pnlInput.add(txtCostPrice);
		   pnlInput.add(lblSellingPrice);
		   pnlInput.add(txtSellingPrice);
		   this.add(pnlInput, BorderLayout.CENTER);
		   
		   
		   pnlBtns=new JPanel();
		   
		   btnAdd=new JButton("Add");
		   
		   btnAdd.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				
				if(!((txtName.getText().equals("")) && txtQuantity.equals("") && txtCostPrice.equals("") && txtSellingPrice.equals(""))){
				Product product=new Product(txtName.getText(), Integer.parseInt(txtQuantity.getText()), Double.parseDouble(txtCostPrice.getText()), Double.parseDouble(txtSellingPrice.getText()), comboItemType.getSelectedIndex());
				
				
				products.add(product);
				
				txtName.setText(null);
				txtQuantity.setText(null);
				txtCostPrice.setText(null);
				txtSellingPrice.setText(null);
				
				JOptionPane.showMessageDialog(null, "The Product was added to  inventory");
				
				}
				
				
				
			}
		});
		   
		   
		   
		   btnView=new JButton("View Products");
		   
		   btnView.addActionListener(new ActionListener() {
				
				@Override
				public void actionPerformed(ActionEvent e) {
					// TODO Auto-generated method stub
					child=new ViewProductGUI(products);
					
					
					
				}
			});
		   
		   pnlBtns.add(btnAdd);
		   
		   pnlBtns.add(btnView);
		   this.add(pnlBtns, BorderLayout.SOUTH);
		   
		   
		   
		   
		   
		   
		   
       	}
	   
	    public static void main(String []args)
	    {
	    	AddProductGUI gui = new AddProductGUI();
	    	gui.setSize(300, 400);
	    	gui.setVisible(true);
	    }

}

**Comment by dublinboy7** [comment]
hiiii

**Comment by dublinboy7** [comment]
hiiiii

**Comment by dublinboy7** [comment]
hiiii
